const { contextBridge, ipcRenderer } = require('electron')
contextBridge.exposeInMainWorld('api', {
  minimize: () => ipcRenderer.send('minimize-window'),
  maximize: () => ipcRenderer.send('maximize-window'),
  close: () => ipcRenderer.send('close-window'),
  onMaximizeChange: (cb) => ipcRenderer.on('window-maximize-change', cb),
  isMaximized: () => ipcRenderer.invoke('is-maximized'),
  getRecientes: () => ipcRenderer.invoke('get-recientes'),
  buscar: (q, filtros) => ipcRenderer.invoke('buscar', q, filtros),
  getServidores: (url) => ipcRenderer.invoke('get-servidores', url),
  checkServidores: (servidores) => ipcRenderer.invoke('check-servidores', servidores),
  getStream: (url) => ipcRenderer.invoke('get-stream', url),
  getAnime: (url) => ipcRenderer.invoke('get-anime', url),
  getFavs: () => ipcRenderer.invoke('get-favs'),
  toggleFav: (anime) => ipcRenderer.invoke('toggle-fav', anime),
  isFav: (url) => ipcRenderer.invoke('is-fav', url),
  getHistorial: () => ipcRenderer.invoke('get-historial'),
  addHistorial: (ep) => ipcRenderer.invoke('add-historial', ep),
  removeHistorial: (link) => ipcRenderer.invoke('remove-historial', link),
  removeProgreso: (link) => ipcRenderer.invoke('remove-progreso', link),
  clearHistorial: () => ipcRenderer.invoke('clear-historial'),
  setProgreso: (link, t, d) => ipcRenderer.invoke('set-progreso', link, t, d),
  getProgreso: (link) => ipcRenderer.invoke('get-progreso', link),
  getTodosProgresos: () => ipcRenderer.invoke('get-todos-progresos'),
  getCalendario: () => ipcRenderer.invoke('get-calendario'),
  getAnimeBiblioteca: (params) => ipcRenderer.invoke('get-anime-biblioteca', params),
  getMangaTendencias: () => ipcRenderer.invoke('get-manga-tendencias'),
  buscarManga:   (q) => ipcRenderer.invoke('buscar-manga', q),
  sugerirManga:  (q) => ipcRenderer.invoke('sugerir-manga', q),
  getMangaDetalle: (url, titulo) => ipcRenderer.invoke('get-manga-detalle', url, titulo),
  getMangaPaginas: (url, sourceIdx) => ipcRenderer.invoke('get-manga-paginas', url, sourceIdx),
  getMangaPortada: (url) => ipcRenderer.invoke('get-manga-portada', url),
  enriquecerAnime: (titulo) => ipcRenderer.invoke('enriquecer-anime', titulo),
  clearCache: () => ipcRenderer.invoke('clear-cache'),
  openBgImage: () => ipcRenderer.invoke('open-bg-image'),
  clearStreamCache: (url) => ipcRenderer.invoke('clear-stream-cache', url),
  getProxyUrl: (url, referer) => ipcRenderer.invoke('get-proxy-url', url, referer),
  configGet:    ()         => ipcRenderer.invoke('config-get'),
  configSet:    (k, v)     => ipcRenderer.invoke('config-set', k, v),
  configSetAll: (data)     => ipcRenderer.invoke('config-set-all', data),
  bgGet:        ()         => ipcRenderer.invoke('bg-get'),
  bgSet:        (dataUrl)  => ipcRenderer.invoke('bg-set', dataUrl),
  appReady:     ()         => ipcRenderer.send('app-ready'),
  onSplashBg:   (cb)       => ipcRenderer.once('splash-screenshot', (_, url) => cb(url)),
  setWinBg:     (color)    => ipcRenderer.send('set-win-bg', color),
  checkNuevosEps: (items)  => ipcRenderer.invoke('check-nuevos-eps', items),
  discordUpdate: (data)    => ipcRenderer.send('discord-update', data),
  discordClear:  ()        => ipcRenderer.send('discord-clear'),
  getMangaSources: ()        => ipcRenderer.invoke('get-manga-sources'),
  getMangaSource:  ()        => ipcRenderer.invoke('get-manga-source'),
  setMangaSource:  (id)      => ipcRenderer.invoke('set-manga-source', id),
  getAnimeSources: ()        => ipcRenderer.invoke('get-anime-sources'),
  getAnimeSource:  ()        => ipcRenderer.invoke('get-anime-source'),
  setAnimeSource:  (id)      => ipcRenderer.invoke('set-anime-source', id),
  onNcPagesMore:  (cb) => ipcRenderer.on('nc-pages-more', (_, pages) => cb(pages)),
  offNcPagesMore: ()   => ipcRenderer.removeAllListeners('nc-pages-more'),
  onNcPagesDone:  (cb) => ipcRenderer.on('nc-pages-done', (_, total) => cb(total)),
  offNcPagesDone: ()   => ipcRenderer.removeAllListeners('nc-pages-done'),
  onAoCFUnlocking: (cb) => ipcRenderer.on('ao-cf-unlocking', (_, v) => cb(v)),
  googleAuth: () => ipcRenderer.invoke('google-auth'),

  // ── AUTO UPDATER ──────────────────────────────────────────────────────────
  onUpdateAvailable: (cb)  => ipcRenderer.on('update-available', (_, v) => cb(v)),
  onUpdateProgress:  (cb)  => ipcRenderer.on('update-progress',  (_, p) => cb(p)),
  onUpdateDownloaded:(cb)  => ipcRenderer.on('update-downloaded', () => cb()),
  updateDownload:    ()    => ipcRenderer.send('update-download'),
  updateInstall:     ()    => ipcRenderer.send('update-install'),
})
